#title: AVERtek # your name photo (or website title) here
logo1: "/images/Company Here.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3><b>AFFORDABLE LUXURY TOWNHOMES</h3></b>
  <br><br>
  <b>ENVISION: TOWNHOME MODELS in 3D</b> - Tour 3D Models Below
  <br><br> 
  <b>EXPERIENCE: 4D AUGMENTED REALITY</b> - AR Walking Tour on Mobile Device
  <br><br>
  <b>VIEW:</b><a href="https://avertek.net/xr-now-model-homes"</b> <b>Designed Living</b></a> 
  <br><br>
  <b>PERSPECTIVE:</b><a href="https://avertek.net/narrative"</b> <b>Testimonials</b></a>
  <br><br>
  <b>EXPLORE:</b><a href="https://avertek.net/contact-us"</b> <b>VIP Tour & Free Gift</b></a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
